# Generated by Django 4.1 on 2023-11-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold_Login_Config',
            fields=[
                ('trigger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trigg_desc', models.TextField()),
                ('thres_description', models.TextField()),
                ('thres_query_logic', models.TextField()),
                ('operation', models.CharField(max_length=50)),
                ('analysis_period', models.CharField(max_length=50)),
                ('num_thresholds_required', models.IntegerField()),
                ('segment_threshold_requirement_flag', models.IntegerField()),
                ('fls_threshold_requirement_flag', models.IntegerField()),
            ],
        ),
    ]
