# Generated by Django 4.1 on 2023-11-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0004_alter_threshold_login_config_fls_threshold_requirement_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold_login_config',
            name='FLS_Threshold_Requirement_Flag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threshold_login_config',
            name='segment_threshold_requirement_flag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
