# Generated by Django 4.1 on 2023-11-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0005_alter_threshold_login_config_fls_threshold_requirement_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation_Parameters',
            fields=[
                ('Task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Channel', models.CharField(max_length=100)),
                ('Subchannel', models.CharField(max_length=100)),
                ('DemoSeg', models.IntegerField()),
                ('ValueSeg', models.IntegerField()),
                ('Segment_id', models.IntegerField()),
                ('Due_Days', models.IntegerField()),
                ('Buffer_Days', models.IntegerField()),
                ('XX_Value', models.IntegerField(blank=True, null=True)),
                ('XX_Type', models.IntegerField(blank=True, null=True)),
                ('PricePoint_Reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Channel_Task_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel', models.CharField(max_length=50)),
                ('Channel_Subchannel_ID', models.IntegerField()),
                ('channel_subchannel_Name', models.CharField(max_length=50)),
                ('DemoSeg_ValueSeg_ID', models.IntegerField()),
                ('DemoSeg_ValueSeg_Name', models.CharField(max_length=255)),
                ('Task', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FLS_Avg_Threshold_Output',
            fields=[
                ('FLS_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Channel', models.CharField(max_length=50)),
                ('Subchannel', models.CharField(max_length=50)),
                ('Channel_Subchannel_ID', models.IntegerField()),
                ('DemoSeg', models.IntegerField()),
                ('ValueSeg', models.IntegerField()),
                ('DemoSeg_ValueSeg_ID', models.IntegerField()),
                ('Trigger_id', models.IntegerField()),
                ('FLSAvg_Threshold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Optimization_Rules',
            fields=[
                ('Task_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Constraint_Description', models.TextField()),
                ('Category_Task_Associated_with', models.CharField(max_length=100)),
                ('Min_Task_Count_FLS', models.IntegerField(blank=True, null=True)),
                ('Max_Task_Count_FLS', models.IntegerField(blank=True, null=True)),
                ('Mutual_Exclusion_Criteria', models.TextField()),
                ('Task_Priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Mix_Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel', models.CharField(max_length=100)),
                ('Subchannel', models.CharField(max_length=100)),
                ('DemoSeg', models.IntegerField()),
                ('ValueSeg', models.IntegerField()),
                ('Focus_Product', models.CharField(max_length=100)),
                ('prod_mix_non_par_annuity_immediate', models.IntegerField()),
                ('prod_mix_non_par_c2p', models.IntegerField()),
                ('prod_mix_non_par_sanchay', models.IntegerField()),
                ('prod_mix_non_par_annuity_pgp', models.IntegerField()),
                ('prod_mix_non_par_health', models.IntegerField()),
                ('prod_mix_par_others', models.IntegerField()),
                ('prod_mix_par_ppt_10', models.IntegerField()),
                ('prod_mix_ul_others', models.IntegerField()),
                ('prod_mix_ul_ppt_10', models.IntegerField()),
                ('prod_mix_ul_single_pre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Segment_Threshold_Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel', models.CharField(max_length=50)),
                ('Subchannel', models.CharField(max_length=50)),
                ('Channel_Subchannel_ID', models.IntegerField()),
                ('DemoSeg', models.IntegerField()),
                ('ValueSeg', models.IntegerField()),
                ('DemoSeg_ValueSeg_ID', models.IntegerField()),
                ('Trigger_id', models.IntegerField()),
                ('Segment_Threshold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task_Closure_Config',
            fields=[
                ('Task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Task_Desc', models.CharField(max_length=255)),
                ('Closure_True_Query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task_Trigger_Mapping',
            fields=[
                ('Task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Task_Desc', models.CharField(max_length=255)),
                ('Task_Stage', models.CharField(max_length=50)),
                ('Trigger', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Trigg_Thres_By_Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel', models.CharField(max_length=50)),
                ('Subchannel', models.CharField(max_length=50)),
                ('Channel_Subchannel_ID', models.IntegerField()),
                ('DemoSeg', models.CharField(max_length=50)),
                ('ValueSeg', models.CharField(max_length=50)),
                ('DemoSeg_ValueSeg_ID', models.IntegerField()),
                ('Trigger_id', models.IntegerField()),
                ('Trigg_Desc', models.CharField(max_length=255)),
                ('Segment_Threshold', models.IntegerField()),
                ('FLSAvg_Threshold', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger_ON_Query_Logic',
            fields=[
                ('Trigger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Trigger_Description_Discussed', models.TextField()),
                ('Assignment_level', models.CharField(max_length=50)),
                ('Iteration_Level', models.CharField(max_length=50)),
                ('Trigger_ON_Query_Logic', models.TextField()),
                ('query', models.TextField()),
            ],
        ),
    ]
