# Generated by Django 4.1 on 2023-11-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0007_alter_task_trigger_mapping_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimization_rules',
            name='Max_Task_Count_FLS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimization_rules',
            name='Min_Task_Count_FLS',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
