# Generated by Django 4.1 on 2023-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0008_alter_optimization_rules_max_task_count_fls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimization_rules',
            name='Task_No',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
