# Generated by Django 4.1 on 2023-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0009_alter_optimization_rules_task_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_parameters',
            name='XX_Type',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocation_parameters',
            name='XX_Value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
