# Generated by Django 4.1 on 2023-11-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0010_alter_allocation_parameters_xx_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_parameters',
            name='Task_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='optimization_rules',
            name='Task_No',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
