# Generated by Django 4.1 on 2023-11-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0011_alter_allocation_parameters_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_parameters',
            name='XX_Type',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocation_parameters',
            name='XX_Value',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
