# Generated by Django 4.1 on 2023-11-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0013_alter_allocation_parameters_buffer_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_mix_focus',
            name='DemoSeg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='ValueSeg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_non_par_annuity_immediate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_non_par_annuity_pgp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_non_par_c2p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_non_par_health',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_non_par_sanchay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_par_others',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_par_ppt_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_ul_others',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_ul_ppt_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_mix_focus',
            name='prod_mix_ul_single_pre',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
