# Generated by Django 4.1 on 2023-11-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0015_alter_product_mix_focus_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_closure_config',
            name='Task_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
