# Generated by Django 4.2.7 on 2023-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_validation", "0016_alter_task_closure_config_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Default_Channel_Trigg_thres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Channel", models.CharField(max_length=50)),
                ("Trigger_id", models.IntegerField()),
                ("Trigg_Desc", models.TextField()),
                ("Segment_Threshold_1", models.IntegerField()),
                ("FLSAvg_Threshold_2", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Microsegment_Default_Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Channel", models.CharField(max_length=100)),
                ("Subchannel", models.CharField(max_length=100)),
                ("DemoSeg", models.FloatField(blank=True, null=True)),
                ("ValueSeg", models.FloatField(blank=True, null=True)),
                ("Segment_id", models.FloatField(blank=True, null=True)),
                ("Default_Tasks", models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Optimization_Rules",
            new_name="Task_Constraint_Rules",
        ),
        migrations.RenameModel(
            old_name="Threshold_Login_Config",
            new_name="Threshold_Logic_Config",
        ),
        migrations.RenameModel(
            old_name="Trigger_ON_Query_Logic",
            new_name="Trigger_ON_Query",
        ),
        migrations.DeleteModel(
            name="FLS_Avg_Threshold_Output",
        ),
        migrations.DeleteModel(
            name="Product_Mix_Focus",
        ),
        migrations.DeleteModel(
            name="Segment_Threshold_Output",
        ),
    ]
