# Generated by Django 4.2.7 on 2023-11-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_validation", "0017_default_channel_trigg_thres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task_closure_config",
            name="Closure_SQL_Query",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
