# Generated by Django 4.1 on 2023-12-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_validation', '0019_product_category_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel_task_mapping',
            old_name='channel_subchannel_Name',
            new_name='Subchannel',
        ),
        migrations.RemoveField(
            model_name='channel_task_mapping',
            name='Channel_Subchannel_ID',
        ),
        migrations.RemoveField(
            model_name='channel_task_mapping',
            name='DemoSeg_ValueSeg_ID',
        ),
        migrations.RemoveField(
            model_name='channel_task_mapping',
            name='DemoSeg_ValueSeg_Name',
        ),
        migrations.AddField(
            model_name='channel_task_mapping',
            name='DemoSeg',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel_task_mapping',
            name='ValueSeg',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel_task_mapping',
            name='Task',
            field=models.CharField(max_length=1000),
        ),
    ]
