# Generated by Django 4.2.7 on 2023-12-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_validation", "0024_alter_allocation_parameters_demoseg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation_parameters",
            name="ValueSeg",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
